# Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm turbo @nestjs/cli
RUN apk add --no-cache libc6-compat openssl procps

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY apps/api/package.json ./apps/api/package.json
COPY packages/database/package.json ./packages/database/package.json
COPY packages/common/package.json ./packages/common/package.json

RUN pnpm install

COPY . .

RUN pnpm --filter @mfo/database exec prisma generate

CMD ["pnpm", "--filter", "@mfo/api", "run", "start:dev"]